### ISSUE TITLE
Issue with Midi Info feed

### ISSUE THREAD

**Issue by caje1** [keotl/ohdieux#11]
First thank you for creating this excellent tool. I'm having an issue with one feed: Midi info (ID: 3858). The length of each episode is 1:21 (it's 11:30 to 1pm with a 9~ min break for news at noon).

When the feed is added, it says the correct length for each episode (1:21). However, when you start playing the episode, it immediately reduces the length and cuts off early. I've attached screenshots.

![Before playing](https://user-images.githubusercontent.com/131814299/234388381-fb55bddf-b160-4feb-b846-5585e248be84.PNG)
![After playing](https://user-images.githubusercontent.com/131814299/234388373-af4d373d-1359-40a8-b7df-f744bf552087.PNG)

**Comment by keotl** [comment]
Unfortunately, this is due to the way Ohdio handles podcasts with multiple segments. These programmes are split into multiple separate audio streams which the app then combines to show as a single episode. As far as I can tell, this is not really easy to replicate with the RSS podcast format.

The best way I have found to work around this is to have each audio stream advertised as a separate episode in the RSS manifest. The two segments should be both available as separate episodes with the same title and description.

![Rattrapage du 24 avr  2023  Des changements à la Loi des transports du Canada, et le divorce entre Tucker Carlson et Fox News](https://user-images.githubusercontent.com/25084248/234500573-3999dea6-90d8-4002-b348-54e6b737ea51.png)

**Comment by caje1** [comment]
Perfect, thank you for explaining!

**Comment by Sytten** [comment]
I checked today and they seem back to one episode?

**Comment by keotl** [comment]
@Sytten I think that would have been caused by a transient network error as it seems to be fine now.
